### ISSUE TITLE
client pass block in danted.conf needs to be dynamically updated

### ISSUE THREAD

**Issue by po1xi548Rysh8BH6** [orangepeelbeef/pia-proxybox#7]
cool tool. I find this useful. I could not get it to work for me until I hand-edited the client pass directive to match my network scope, however.

**Comment by orangepeelbeef** [comment]
Thanks for the report I'll take a look!

**Comment by orangepeelbeef** [comment]
Yeah I see what you mean, looks like what I did for squid.conf was just set all the RFC1918 space in the acl

That would be the easiest, otherwise definitely needs to be dynamic as you suggest

**Comment by orangepeelbeef** [comment]
sorry it took me so long!
